name: CI & CD

on:
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

jobs:
  test:
    name: ‚úÖ Unit & integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cache
        uses: coursier/cache-action@v6.1
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.2.0'
          java: 'java11'
      - name: Install python
        run: gu install python
      - name: Python environment
        run: graalpython -m venv ${JAVA_HOME}/languages/python/scala-pygments/
      - name: Install pygments
        run: ${JAVA_HOME}/languages/python/scala-pygments/bin/pip install Pygments
      - name: Tests
        run: sbt +test +It/test
  lint:
    name: ‚ö†Ô∏è Fatal warnings and code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cache
        uses: coursier/cache-action@v6.1
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.2.0'
          java: 'java11'
      - name: Code formatting
        run: sbt scalafmtCheckAll
      - name: Fatal warnings
        run: sbt -Dmode=strict +compile
  deploy:
    name: üöÄ Deploy
    needs: [ test, lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cache
        uses: coursier/cache-action@v6.1
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.2.0'
          java: 'java11'
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{secrets.PGP_PASSPHRASE}}
          PGP_SECRET: ${{secrets.PGP_SECRET}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}